const gpio = require('wiring-pi');
const HALL = 25;
const MotorPin = 29;
const MotorPin2 = 27;
const GreenColor = 3;
const BlueColor = 23;
const RedColor = 24;
const Buzzer = 6;
gpio.wiringPiSetup();
gpio.pinMode(HALL,gpio.INPUT);
gpio.pinMode(MotorPin,gpio.OUTPUT);
gpio.pinMode(MotorPin2,gpio.OUTPUT);
gpio.pinMode(RedColor,gpio.OUTPUT);
gpio.pinMode(BlueColor,gpio.OUTPUT);
gpio.pinMode(GreenColor,gpio.OUTPUT);
gpio.pinMode(Buzzer,gpio.OUTPUT);
gpio['HALL'] = HALL;
gpio['MotorPin'] = MotorPin;
gpio['MotorPin2'] = MotorPin2;
gpio['Red'] = RedColor;
gpio['Blue'] = BlueColor;
gpio['Green'] = GreenColor;
gpio['Buzzer'] = Buzzer;
module.exports = gpio;
