const gpio = require('wiring-pi');
const TRIG = 25;
const ECHO = 28;
const SOUND = 22;
const FLAME = 21;
const TILT = 29;
const DHT = 4;
gpio.wiringPiSetup();
gpio.pinMode(ECHO,gpio.INPUT);
gpio.pinMode(TRIG,gpio.OUTPUT);
gpio.pinMode(SOUND,gpio.INPUT);
gpio.pinMode(FLAME,gpio.INPUT);
gpio.pinMode(TILT,gpio.INPUT);
gpio['TRIG'] = TRIG;
gpio['ECHO'] = ECHO;
gpio['SOUND'] = SOUND;
gpio['FLAME'] = FLAME;
gpio['TILT'] = TILT;
gpio['DHT'] = DHT;
module.exports = gpio;
